import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Topbar from "@/components/shared/navigation/Topbar";
import {ThemeProvider} from "@/components/providers/theme-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({children}: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Topbar />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
